### PR TITLE
ENH force pthreads

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks @beckermr.

The bot seems to be using a very old pinning file. So have re-rendered locally and pushed to your branch. Should help this move forward while we sort out that issue.

**Comment by beckermr** [comment]
Might this have been the cloudfare thing with old indices?

**Comment by jakirkham** [comment]
That was my suspicion as well. We had to redeploy the bot earlier today. So it sounds like it was affected. Going to try redeploying it again.

**Comment by jakirkham** [comment]
Bot is redeployed with the new pinning file. Let's test to see if it is working. Should be a no-op.

@conda-forge-admin, please re-render.

**Comment by beckermr** [comment]
Looks like we are good to go here @conda-forge/pyfftw. Shall we merge and get on with it?

**Comment by grlee77** [comment]
Thanks @beckermr!

**Pull request merged**
