### PR TITLE
WIP, RFC: Try wheels

### PR DESCRIPTION
**Pull request by jakirkham**
Pending the outcome of the discussion in issue ( https://github.com/conda-forge/conda-smithy/issues/608 ).

Attempts to build a wheel of pyfftw for those wishing to pip install it instead of conda install it. This relies on a not totally finalized version of `conda-smithy` to get `conda-build` 3, which simplified this exercise. The wheels built will not be one-to-one with typical wheels in all cases. For example, we build on CentOS 6 instead of CentOS 5 used by manylinux1. Also we build with the macOS 10.9 SDK instead of 10.6. Though the wheels I built locally seem to match this. As for Windows this should be a close match to what is expected.

### CODE REVIEW

**Comment by jakirkham** [comment]
Should add I don't know if our upload script can handle this. So that is something we might need to look at.

**Comment by jakirkham** [comment]
For some reason, the wheel here didn't pull in `numpy` when installing `pyFFTW`. However had no similar issue with another use case ( seen in PR https://github.com/conda-forge/numcodecs-feedstock/pull/17 ), which also requires `numpy` and pulled it in without issues. So am inclined to believe there is some issue in `pyFFTW`'s `setup.py`, which needs correcting.

**Comment by grlee77** [comment]
> For some reason, the wheel here didn't pull in numpy when installing pyFFTW.

Perhaps pyFFTW/pyFFTW#204 would help?  It adds a `pyproject.toml` file for PEP-518 listing numpy as a requirement.

**Comment by jakirkham** [comment]
Not sure. That only requires `numpy` for the build, not the install, right? The issue was coming in when installing the binary wheel after the build for some reason.

It might be that we are being too clever for our own good in `setup.py`. Nothing stuck out at me when I was putting this PR together, but I could just be overlook something. Thoughts welcome. :)

**Comment by jakirkham** [comment]
Would you be able to test this, @grlee77? Given you have been looking at `setup.py` a lot more than I, it may be more obvious to you what we are missing when playing with the wheels this produces.

**Comment by grlee77** [comment]
I think I have found the error here:
https://github.com/pyFFTW/pyFFTW/blob/f4bdbfcad95b42fb1b0705c084d17f2d39d1d0a7/setup.py#L744-L760
`install_requires` is set to build_requires, but `build_requires` doesn't contain numpy if it was already importable on the system.  We need to make sure that NumPy always shows up in `install_requires` and I think that should fix it.

**Comment by grlee77** [comment]
see pyFFTW/pyFFTW/#210 for a potential fix

**Comment by jakirkham** [comment]
That did the trick. Thanks @grlee77. :)

**Comment by jakirkham** [comment]
In the interest of progressing this a little further, we could try uploading these to a different label (e.g. `test` instead of `main`). I'm not sure if the upload script would work, but this would be a good way to test it. If the upload does work, this would allow people to play with these and provide feedback.

**Comment by jakirkham** [comment]
Creating a `test` branch that uploads to a `test` label in PR ( https://github.com/conda-forge/pyfftw-feedstock/pull/18 ). Once that is in, we can retarget this PR at the `test` branch and merge to try and get the wheels out under the `test` label so we can further this discussion.

**Comment by jakirkham** [comment]
@conda-forge-admin, please lint.

**Comment by grlee77** [comment]
@jakirkham: is there any interest in keeping this open?
we eventually got things working over at https://github.com/pyFFTW/pyFFTW-wheels

**Comment by jakirkham** [comment]
Sorry should have followed up here. Agree we can close this out. Will do so now

**Pull request closed without merging**
