### PR TITLE
Static link

### PR DESCRIPTION
**Pull request by grlee77**
This PR is to build against static FFTW libs on linux to fix the following issue on linux when both pyFFTW and MKL numpy are installed:
pyFFTW/pyFFTW#40
see more details in conda-forge/fftw-feedstock#4

It is not expected that this will pass CI until after conda-forge/fftw-feedstock#4 is merged, so I used `[skip ci]` for now.

I had to patch setup.py to link the static libraries rather than the dynamic ones.  I have opened pyFFTW/pyFFTW#116 to see about maybe getting this functionality merged upstream and remove the need for the patch.

The changes in this PR are not needed when pyFFTW is used with the numpy from conda-forge, but are necessary if a user is using MKL numpy from the defaults channel on a linux system.  

One unresolved issue:  I don't see any easy way to verify the fix via CI because I don't know how to force an MKL version of numpy during the testing stage (the openblas version gets selected).  I have verified that this does resolve the issue when testing locally with MKL numpy.

### CODE REVIEW

**Comment by jakirkham** [comment]
Feel free to drop the `[skip ci]`. Also, please ping me to restart CIs when the FFTW change is released (in case I forget).

**Comment by grlee77** [comment]
Okay, CI is passing.  The main issue is that the MKL conflicts aren't really getting tested by `run_test.py` since the openblas variant of numpy is installed.

**Comment by jakirkham** [comment]
Are you sure? Seeing `mkl` [here]( https://travis-ci.org/conda-forge/pyfftw-feedstock/jobs/135136189#L667 ). In fact, I'm a little concerned that it is showing up.

**Comment by jakirkham** [comment]
Actually I have seen this weirdness in the test phase before.

**Comment by jakirkham** [comment]
@grlee77, since this is now statically linking to FFTW, can we drop the FFTW run time dependency too?

**Comment by jakirkham** [comment]
@hgomersall, can I convince you to take a look at the patch we are using here? It would be nice if we could add an option to `pyfftw`'s `setup.py` that allows a user to go down this route or perhaps even makes it default behavior that one can opt-out from.

**Comment by jakirkham** [comment]
Also, could you try disabling the patch @grlee77 so that we can see the bug you were encountering?

**Comment by grlee77** [comment]
trying without fftw run dependency now.

I put a version with the static linking commented out as #6.  Assuming the MKL bumpy is used, hopefully that will demonstrate the problem

**Comment by hgomersall** [comment]
Yes, I'm happy to merge this - it seems like a sensible fix to a silly problem. I've suggest a small refactor in #116 which I'll immediately merge after implemented.

**Comment by grlee77** [comment]
updated the patch to match what was just merged in pyFFTW/pyFFTW#116

In the current implementation here both OS X and Linux are statically linked.  As the issue doesn't seem to occur on OS X, it would be possible to modify the recipe to leave dynamic linking there if that is preferred.

**Comment by grlee77** [comment]
pyFFTW 0.10.2 was just released so I thought the patch should no longer be needed.  have to look into why this is failing now.

**Comment by grlee77** [comment]
I think there must have been a bad upload of pyFFTW to pypi as the expected changes for static linking aren't included in the `setup.py` included there.  However the 0.10.2 available via the github releases page does have the expected changes.  issue opened at pyFFTW/pyFFTW#118

**Comment by grlee77** [comment]
Updated to the 0.10.3 release from `pypi`.  I was finally able to replicate the expected errors via CI in #6.  The failure is dependent on `numpy` being imported prior to `pyfftw` so I have removed the import tests that were causing the error not to occur.  Now that we have a `run_test.py` script, those import tests weren't adding anything.

**Comment by grlee77** [comment]
for some reason, it doesn't look like the `-Wl,-Bsymbolic` flag is getting added on linux as expected which is leading to the failure.

**Comment by grlee77** [comment]
I think I fixed the spacing issue that was leading to the linking error.  Now there is a capacity error:
```
Error: HTTPError: 503 Server Error: Service Unavailable: Back-end server is at capacity for url: https://repo.continuum.io/pkgs/free/linux-64/pip-8.1.1-py27_1.tar.bz2:
```
will try restarting the again CI later

**Comment by jakirkham** [comment]
Yeah, I've seen that a few times too. Seems to be resolved now.

Thanks for this fix, @grlee77. Thanks @hgomersall for working with us on the patch.

LGTM. Seems we still have WIP in the title. Were there more changes you were planning to add @grlee77 or can we merge this?

**Comment by grlee77** [comment]
nothing else.  unless you would prefer to switch the linking back to dynamic in the OS X case?  I guess the main advantage would be a smaller package size.

**Comment by jakirkham** [comment]
If I have to chose between potential bugs and a larger package size, I will always pick the latter. 😄

**Comment by jakirkham** [comment]
Thanks again for your hard work on this, @grlee77.

**Pull request merged**
