### PR TITLE
pyFFTW Threading Errors

### PR DESCRIPTION
**Pull request by karlotness**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)

While using pyfftw from conda-forge I've run into some of the issues reported in #51 and #59. It looks like setup.py doesn't pass the required link flags for pthread causing the detection to fail. I think this should fix that problem.

I also added an upper bound for Cython since pyFFTW there seem to be a few compatibility issues with v3.0.

Thanks!

### CODE REVIEW

**Comment by karlotness** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Thanks Karl! 🙏

Appreciate you taking the time to dig into this

Is there some kind of test we can to ensure this keeps working?

**Comment by jakirkham** [comment]
Also sorry for missing this until now 😞  Have not really been that active here of late

**Comment by karlotness** [comment]
No problem at all, I just thought I would mention it since I got a notification from the issue thread.

For the test, I think the reason the current test didn't catch it is that the exception generated is unraisable. Eventually updating to Cython 3 should also fix this since the `cdef` functions would by default correctly propagate exceptions. For the moment though we can just be sure to also fail the tests on unraisable exceptions and I've tried to do that here.

In a quick test with a local build the test did fail without the other patch and passes with it so I think this should help detect this particular problem, at least.

**Review by ax3l — APPROVED** [review]

**Comment by tskisner** [comment]
Hi there, fixing #51 and #59 would be really useful for some of my projects.  If this fixes those issues, is there an ETA for getting this merged?  Do you need any help with additional testing?

**Comment by paugier** [comment]
This PR seems reasonable. It would be great to have this new build available for users!

**Comment by jakirkham** [comment]
I think we need some new maintainers of this feedstock. If some of the folks in this thread would be interested in taking on that role, would be happy to help add you here

**Comment by paugier** [comment]
>   If some of the folks in this thread would be interested in taking on that role, would be happy to help add you here

I would be happy to help if it is useful.

**Comment by jakirkham** [comment]
Thanks @paugier ! 🙏

Please send a new PR adding yourself to the recipe's maintainer list

**Comment by stellarpower** [comment]
Is there a workaround for this. Currently it seems I'm not able to use the package.

**Comment by paugier** [comment]
> Please send a new PR adding yourself to the recipe's maintainer list

I finally took the time to do it!

**Comment by paugier** [comment]
@conda-forge-admin, please rerender

**Comment by paugier** [comment]
@karlotness would you be able to work on this old PR? 

What I think is needed:

- rebase
- SPDX license
- no Python 3.12 (this version of pyFFTW does not support it)
- add `{{ stdlib("c") }}`

Then there is the error on osx that I don't understand...

Note that pyFFTW 0.14.0 should be released very soon, so we can also give up this PR and try to build this new version later.

**Comment by karlotness** [comment]
@conda-forge-admin, please rerender

**Comment by karlotness** [comment]
Thanks for taking a look. I went through and made those updates. I'm not sure either on the macOS build failures, but it looks like the problem might be with the test builds that the setup script runs to detect whether certain functions are supported. Maybe it can't find the headers. I made a change to the build script to see if that does anything.

**Comment by karlotness** [comment]
@conda-forge-admin, please rerender

**Comment by karlotness** [comment]
@paugier Ok I think this should be set. Looks like the failures on macOS were due to Apple Clang being more strict on implicit function definitions. Ideally the headers would be imported correctly, but the link step still works ok if we suppress the errors (the same warning is also happening in the Linux builds).

I also turned on cross compilation for the Linux ppcle64 and aarch64 builds since some earlier native builds on Travis were cancelled (I think it's generally a bit flaky).

**Comment by paugier** [comment]
Thanks a lot @karlotness ! Good that we have a working conda build for 0.13.1. We will soon have to play again with conda since pyFFTW will be released in few hours :slightly_smiling_face:

**Comment by karlotness** [comment]
Thanks @paugier! One thing though, it looks like one of the mac jobs died with a random error. If you click through the failed checkmark on the commit from the main repo page, I think GitHub should have a button to "rerun failed checks". If we can just get that one job to run again it should go through.

**Comment by paugier** [comment]
Oups... I restarted everything. Let's see.

**Comment by karlotness** [comment]
Looks like that worked out fine, the missing build is there now. Thanks!

And just as a side note, I think in theory this should also close #59, #63, and pyFFTW/pyFFTW#294

**Pull request merged**
