### PR TITLE
update to v0.13.0

### PR DESCRIPTION
**Pull request by grlee77**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by grlee77** [comment]
In addition to bumping the version, I removed the static linking of FFTW here. That static linking was intentionally done previously to avoid issues where NumPy in the default channel used to monkey patch `np.fft` functions with their `mkl_fft` equivalents and symbols from `mkl_fft` could shadow those from pyFFTW. (See: https://github.com/pyFFTW/pyFFTW/issues/40, https://github.com/pyFFTW/pyFFTW/issues/106). This lead to issues where behavior could depend on the import order of NumPy vs. pyFFTW. As far as I can tell, NumPy packages for the last several release do not do this and just rely on its own pocketfft-based FFT by default, so I don't think this is still an issue.

**Comment by grlee77** [comment]
I marked Python 3.8 on osx-arm64 as skipped for now. The failure there does not look obviously related to pyFFTW itself (seems to occur prior to the start of compilation):

<details>

```
Setting up cross-python
Finished setting up cross-python
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/venv/lib/site.py", line 180, in <module>
    import site
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<string>", line 18, in _PathFinder_find_spec
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/lib/python3.8/sysconfig.py", line 534, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/lib/python3.8/sysconfig.py", line 524, in get_paths
    return _expand_vars(scheme, vars)
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/lib/python3.8/sysconfig.py", line 177, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/lib/python3.8/sysconfig.py", line 572, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/lib/python3.8/sysconfig.py", line 439, in _init_posix
    name = _get_sysconfigdata_name(True)
TypeError: _get_sysconfigdata_name() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "/Users/runner/miniforge3/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 215, in main
    call_conda_build(action, config)
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 187, in call_conda_build
    result = api.build(
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 2206, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/utils.py", line 410, in check_call_env
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/work/conda_build.sh']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
```

<\details>

**Comment by grlee77** [comment]
I marked Python 3.8 on osx-arm64 as skipped for now. The failure there does not look obviously related to pyFFTW itself (seems to occur prior to the start of compilation):

<details>

```
Setting up cross-python
Finished setting up cross-python
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/venv/lib/site.py", line 180, in <module>
    import site
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "<string>", line 18, in _PathFinder_find_spec
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/lib/python3.8/sysconfig.py", line 534, in get_path
    return get_paths(scheme, vars, expand)[name]
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/lib/python3.8/sysconfig.py", line 524, in get_paths
    return _expand_vars(scheme, vars)
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/lib/python3.8/sysconfig.py", line 177, in _expand_vars
    _extend_dict(vars, get_config_vars())
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/lib/python3.8/sysconfig.py", line 572, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/_build_env/lib/python3.8/sysconfig.py", line 439, in _init_posix
    name = _get_sysconfigdata_name(True)
TypeError: _get_sysconfigdata_name() takes 0 positional arguments but 1 was given
Traceback (most recent call last):
  File "/Users/runner/miniforge3/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 215, in main
    call_conda_build(action, config)
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/boa/cli/mambabuild.py", line 187, in call_conda_build
    result = api.build(
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/build.py", line 2206, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/utils.py", line 410, in check_call_env
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/Users/runner/miniforge3/conda-bld/pyfftw_1640654785474/work/conda_build.sh']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
```

<\details>

**Comment by grlee77** [comment]
I opened #49 regarding the skip statement that was added here. I think we can probably merge this as is now and address that somewhat niche case later.

Regarding the license listed in the recipe, now that we have removed the static linking, I am wondering if we should change it to simply state `BSD 2-clause` which is how the Python code is licensed? (It is the underlying FFTW library that is GPL-licensed and we are now no longer statically linking that in this feedstock). @hgomersall, @jakirkham what do you think?

**Comment by hgomersall** [comment]
Apologies, I've been away for a few days. License issues seem fine (they're for this repo right?)

**Comment by grlee77** [comment]
> License issues seem fine (they're for this repo right?)

No, the license and file name listed here:
https://github.com/conda-forge/pyfftw-feedstock/blob/8a480e00a2b397ed3ba22e6c47354e2097eb7461/recipe/meta.yaml#L39-L40

refers to the bundled code (i.e. pyFFTW itself), not the recipe code in this repo. Previously we were statically linking FFTW here so I think that is why GPL2 was listed there in addition to pyFFTW's BSD license. We can potentially drop mention of GPL in this recipe as that is [already mentioned](https://github.com/conda-forge/fftw-feedstock/blob/972ca75b022acd0b8c7c90b7b9a7fb11ca0d813c/recipe/meta.yaml#L128) in the separate FFTW feedstock that is a requirement of this one.

**Pull request merged**
