### PR TITLE
Add paugier as maintainer

### PR DESCRIPTION
**Pull request by paugier**
The goal of this PR is not to build a new package but only to add me as maintainer as asked here https://github.com/conda-forge/pyfftw-feedstock/pull/60#issuecomment-1945375867 

Unfortunately, this conda-forge package is not maintained anymore. The last conda package is not usable (see for example https://github.com/conda-forge/pyfftw-feedstock/pull/60#issuecomment-2052600398).

A new pyFFTW version will soon be released on PyPI and it would be good to fix the conda package before.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by paugier** [comment]
Note that I invested quite a lot of time in pyFFTW recently as seen for example in https://github.com/pyFFTW/pyFFTW/pulls?q=is%3Apr+is%3Aclosed

**Review by hgomersall — APPROVED** [review]

**Comment by hgomersall** [comment]
It's hard to argue against the necessity of more help here!

**Comment by hgomersall** [comment]
Any objections?

**Comment by jakirkham** [comment]
+1 from me

**Comment by jakirkham** [comment]
Thanks Pierre and Henry! 🙏

**Pull request merged**
